repos:
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.6.2
    hooks:
      - id: prettier
        types_or:
          - toml
          - css
          - json
          - json5
          - markdown
          - yaml
        additional_dependencies:
          - prettier
          - prettier-plugin-toml
        args:
          - --cache
          - --cache-location=.prettier-cache
          - --ignore-path=.gitignore
  - repo: https://github.com/eslint/eslint
    rev: v9.35.0
    hooks:
      - id: eslint
        args:
          - --fix
  - repo: meta
    hooks:
      - id: check-hooks-apply
        name: check-hooks-apply
      - id: check-useless-excludes
        name: check-useless-excludes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        name: trailing-whitespace
      - id: end-of-file-fixer
        name: end-of-file-fixer
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.1
    hooks:
      - id: ruff-check
        args:
          - --fix
      - id: ruff-format
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.18.1
    hooks:
      - id: markdownlint-cli2
        name: markdownlint-readme
        files: ^README.md
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 3.4.0
    hooks:
      - id: editorconfig-checker
        name: editorconfig-checker
        alias: ec
  - repo: https://github.com/tcort/markdown-link-check
    rev: v3.13.7
    hooks:
      - id: markdown-link-check
        name: markdown-link-check
        files: ^README\.md$
        args:
          - --config
          - .markdown-link-check.json
