name: pre-commit autoupdate

on:
  schedule:
    - cron: 0 3 1 1/6 *
  workflow_dispatch:

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: j178/prek-action@v1
        with:
          extra_args: 'autoupdate'
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3.10.0
        with:
          token: ${{ secrets.PRECOMMIT_AUTOUPDATE_TOKEN }}
          branch: update/prek-autoupdate
          title: Update prek hooks
          commit-message: Update prek hooks versions
          body: Update versions of prek tools to latest version.
          labels: dependencies
          delete-branch: true
