name: prek

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  prek:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v5
        with:
          node-version-file: .nvmrc
      - name: Install dependencies
        run: npm ci
      - uses: actions/checkout@v5
      - uses: j178/prek-action@v1
